# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.1.0
_src_path: https://github.com/napari/napari-plugin-template
display_name: Object Rf
email: michaelseelion@outlook.com
full_name: Chuyao Wang
github_repository_url: https://github.com/chuyaowang/object-xgb
github_username_or_organization: chuyaowang
include_reader_plugin: true
include_sample_data_plugin: true
include_widget_plugin: true
include_writer_plugin: true
install_dependabot: true
install_precommit: true
license: MIT
module_name: object_xgb
plugin_name: object-xgb
short_description: Object classification using random forest.
